spring.application.name=doner-cloud
greeting.welcome=You are using ${spring.application.name}

spring.thymeleaf.cache=false

##DataSource
spring.datasource.url=jdbc:postgresql://localhost/donercloud
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=none

##Google OAuth
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_USER}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_PASSWORD}
spring.security.oauth2.client.registration.google.scope=openid,profile,email


#SSl/TLS
server.port=8443
server.ssl.key-store=file:///C:/Users/user/mykeys.jks
server.ssl.key-store-password=Astanaletmein
server.ssl.key-password=Astanaletmein