spring.application.name=doner-cloud

spring.thymeleaf.cache=false

spring.datasource.generate-unique-name=false
spring.datasource.name=donercloud

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_USER}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_PASSWORD}
spring.security.oauth2.client.registration.google.scope=openid,profile,email